/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface SpinEntry {
  'selectedLabel' : string,
  'selectedWeight' : bigint,
  'timestamp' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Wheel {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'options' : Array<WheelOption>,
}
export interface WheelInput { 'name' : string, 'options' : Array<WheelOption> }
export interface WheelOption {
  'id' : string,
  'weight' : bigint,
  'optionLabel' : string,
  'color' : [] | [string],
  'enabled' : boolean,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createWheel' : ActorMethod<[WheelInput], Wheel>,
  'deleteWheel' : ActorMethod<[string], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getSpinHistory' : ActorMethod<[string], Array<SpinEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWheel' : ActorMethod<[string], [] | [Wheel]>,
  'getWheels' : ActorMethod<[], Array<Wheel>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'spinWheel' : ActorMethod<[string], [] | [SpinEntry]>,
  'updateWheel' : ActorMethod<[string, WheelInput], [] | [Wheel]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];