/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const WheelOption = IDL.Record({
  'id' : IDL.Text,
  'weight' : IDL.Nat,
  'optionLabel' : IDL.Text,
  'color' : IDL.Opt(IDL.Text),
  'enabled' : IDL.Bool,
});
export const WheelInput = IDL.Record({
  'name' : IDL.Text,
  'options' : IDL.Vec(WheelOption),
});
export const Wheel = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'options' : IDL.Vec(WheelOption),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SpinEntry = IDL.Record({
  'selectedLabel' : IDL.Text,
  'selectedWeight' : IDL.Nat,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createWheel' : IDL.Func([WheelInput], [Wheel], []),
  'deleteWheel' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSpinHistory' : IDL.Func([IDL.Text], [IDL.Vec(SpinEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWheel' : IDL.Func([IDL.Text], [IDL.Opt(Wheel)], ['query']),
  'getWheels' : IDL.Func([], [IDL.Vec(Wheel)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'spinWheel' : IDL.Func([IDL.Text], [IDL.Opt(SpinEntry)], []),
  'updateWheel' : IDL.Func([IDL.Text, WheelInput], [IDL.Opt(Wheel)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const WheelOption = IDL.Record({
    'id' : IDL.Text,
    'weight' : IDL.Nat,
    'optionLabel' : IDL.Text,
    'color' : IDL.Opt(IDL.Text),
    'enabled' : IDL.Bool,
  });
  const WheelInput = IDL.Record({
    'name' : IDL.Text,
    'options' : IDL.Vec(WheelOption),
  });
  const Wheel = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'options' : IDL.Vec(WheelOption),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SpinEntry = IDL.Record({
    'selectedLabel' : IDL.Text,
    'selectedWeight' : IDL.Nat,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createWheel' : IDL.Func([WheelInput], [Wheel], []),
    'deleteWheel' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSpinHistory' : IDL.Func([IDL.Text], [IDL.Vec(SpinEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWheel' : IDL.Func([IDL.Text], [IDL.Opt(Wheel)], ['query']),
    'getWheels' : IDL.Func([], [IDL.Vec(Wheel)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'spinWheel' : IDL.Func([IDL.Text], [IDL.Opt(SpinEntry)], []),
    'updateWheel' : IDL.Func([IDL.Text, WheelInput], [IDL.Opt(Wheel)], []),
  });
};

export const init = ({ IDL }) => { return []; };